### ISSUE TITLE
Why limiting the module to the Regensburger Verkehrsverbund?

### ISSUE THREAD

**Issue by gprezza** [sebikolon/MMM-RVV#1]
Hi!
first of all I would like to thank you for developing this module, it's awesome.
I don't understand just one thing: since the data are pulled from bayern-fahrplan.de, why do the module docs (and even its name!) seem to restrict it to the RVV system? For example, this module works perfectly fine with the "München Hbf" stop in Munich, which is defined by stop_from_ID 91000100. Why not saying that this module is a departure monitor for local transport in the entire state of Bavaria (with data taken from bayern-fahrplan.de)?

**Comment by SeBuCX** [comment]
Hey! 
Nice that you spotted this project and contributed immediately.
You're completely right. The reason for this limitation is: Initially I only had the need to get it running for the Regensburg area - because of a lack of time a more generalized version didn't made it to github yet.

So thank you very much for the little improvements.
If you have any ideas how to pimp the functionality / provide more options for easy layout changes using the module config, let me know ;-)

**Comment by gprezza** [comment]
I see! 
Might be worth updating the module description on the MagicMirror 3rd party modules page to specify that it works for the whole of Bavaria (I can do it if you don't have time). Maybe also the module name can be updated? Although it's not really necessary.

Anyways, I'll be using this module (I really like the green bar that shows the updating status! :) ). If anything else comes up I'll see what I can do; though I have no experience with Javascript and to be honest it's already surprising that I managed to fix the multiple instances issue.

**Comment by SeBuCX** [comment]
Great. If we really want to extend the module to support stops across all Bavaria, we'd need to update the link description as well as the module names + class names -> entire refactoring.

If you do this (I appreciate your help), please test carefully and put examples and screenshots for certain different stops, not only the _Regensburg Universität_ example. I want to maintain a high quality on this project.

Even an i18n support would be nice, right now the translations for special cases (like trip was cancelled) is only on german, this would also be an improvement. Feel free :)

**Comment by gprezza** [comment]
If it's just renaming some variables/classes and translating, I should be able to do it. I'll work on it in the next days/weeks :)
